import type { Product } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    title: "Title title title title title title title",
    image: "/3d-green-dragon-model.jpg",
    seller: "User User ...",
    rating: 4.9,
    price: 5,
    category: "Unity",
    description: "Here I am selling you one of the most hardworking internet slaves straight from FRI",
    tags: ["TAG1", "TAG2", "TAG3", "TAG4", "TAG5"],
    fileSize: "x GB",
    views: 0,
    sales: 0,
  },
  {
    id: "2",
    title: "Title title title title title title title",
    image: "/person-wearing-hoodie-sunset.jpg",
    seller: "User User ...",
    rating: 4.9,
    price: 5,
    category: "Images",
    description: "Here I am selling you one of the most hardworking internet slaves straight from FRI",
    tags: ["TAG1", "TAG2", "TAG3", "TAG4", "TAG5"],
    fileSize: "x GB",
  },
  {
    id: "3",
    title: "Title title title title title title title",
    image: "/blue-robot-icon-illustration.jpg",
    seller: "User User ...",
    rating: 4.9,
    price: 5,
    category: "Code",
    description: "Here I am selling you one of the most hardworking internet slaves straight from FRI",
    tags: ["TAG1", "TAG2", "TAG3", "TAG4", "TAG5"],
  },
  {
    id: "4",
    title: "Title title title title title title title",
    image: "/person-with-yellow-flowers-outdoors.jpg",
    seller: "User User ...",
    rating: 4.9,
    price: 5,
    category: "Images",
    description: "Here I am selling you one of the most hardworking internet slaves straight from FRI",
    tags: ["TAG1", "TAG2", "TAG3", "TAG4", "TAG5"],
  },
  {
    id: "5",
    title: "Title title title title title title title",
    image: "/collage-of-diverse-people-portraits.jpg",
    seller: "User User ...",
    rating: 4.9,
    price: 5,
    category: "Images",
    description: "Here I am selling you one of the most hardworking internet slaves straight from FRI",
    tags: ["TAG1", "TAG2", "TAG3", "TAG4", "TAG5"],
  },
  {
    id: "6",
    title: "Title title title title title title title",
    image: "/red-sports-cars-3d-render.jpg",
    seller: "User User ...",
    rating: 4.9,
    price: 5,
    category: "Unity",
    description: "Here I am selling you one of the most hardworking internet slaves straight from FRI",
    tags: ["TAG1", "TAG2", "TAG3", "TAG4", "TAG5"],
  },
  {
    id: "7",
    title: "Title title title title title title title",
    image: "/aerial-view-of-winding-road.jpg",
    seller: "User User ...",
    rating: 4.9,
    price: 5,
    category: "Images",
    description: "Here I am selling you one of the most hardworking internet slaves straight from FRI",
    tags: ["TAG1", "TAG2", "TAG3", "TAG4", "TAG5"],
  },
  {
    id: "8",
    title: "Title title title title title title title",
    image: "/silhouette-of-car-at-sunset.jpg",
    seller: "User User ...",
    rating: 4.9,
    price: 5,
    category: "Images",
    description: "Here I am selling you one of the most hardworking internet slaves straight from FRI",
    tags: ["TAG1", "TAG2", "TAG3", "TAG4", "TAG5"],
  },
  {
    id: "9",
    title: "Title title title title title title title",
    image: "/human-race-board-game.jpg",
    seller: "User User ...",
    rating: 4.9,
    price: 5,
    category: "Images",
    description: "Here I am selling you one of the most hardworking internet slaves straight from FRI",
    tags: ["TAG1", "TAG2", "TAG3", "TAG4", "TAG5"],
  },
  {
    id: "10",
    title: "Title title title title title title title",
    image: "/colorful-3d-cat-model.jpg",
    seller: "User User ...",
    rating: 4.9,
    price: 5,
    category: "Unity",
    description: "Here I am selling you one of the most hardworking internet slaves straight from FRI",
    tags: ["TAG1", "TAG2", "TAG3", "TAG4", "TAG5"],
  },
  {
    id: "11",
    title: "Title title title title title title title",
    image: "/abstract-colorful-lines-pattern.jpg",
    seller: "User User ...",
    rating: 4.9,
    price: 5,
    category: "Images",
    description: "Here I am selling you one of the most hardworking internet slaves straight from FRI",
    tags: ["TAG1", "TAG2", "TAG3", "TAG4", "TAG5"],
  },
  {
    id: "12",
    title: "Title title title title title title title",
    image: "/cute-hamster-toy.jpg",
    seller: "User User ...",
    rating: 4.9,
    price: 5,
    category: "Unity",
    description: "Here I am selling you one of the most hardworking internet slaves straight from FRI",
    tags: ["TAG1", "TAG2", "TAG3", "TAG4", "TAG5"],
  },
]
